language: "ru"
tone_instructions: |
  Будьте вежливы и конструктивны.
  Используйте русский язык для общения.
  Фокусируйтесь на улучшении качества кода.

reviews:
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!*.md"
    - "!*.txt"
    - "!docs/**"
    - "!*.log"
    - "!debug_screenshots/**"
    - "!logs/**"

chat:
  auto_reply: true
